# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c79b825e4f85ad054171eb7b667b280e78110a45b2e41595dc35a872b79e005aa07ca9e2e280e5c3377adc1bc8f6efc545c25f436e723b54c5aed73f1374bb

test:
  secret_key_base: 3a40d07b2e1605a87bd51d1922723433cee2700fbf9ab1011014bca58ac07145f1b64ac21664a92950959a8e4648777b6b767c073ee8e2c10799d5ad48c4017b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
